# Generated by Django 5.2.11 on 2026-06-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='fssai_license_number',
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gst_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
