# Generated by Django 5.2.11 on 2026-06-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_dynamic_delivery_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='driving_license_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deliverypartnerprofile',
            name='rc_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
